config/routes.rb
Rails.application.routes.draw do

  get '/users/:user_id/joined' => 'learn/courses#joined', as: 'user_joined_courses'
  namespace :learn do
    get '/', to: redirect('/learn/courses/questions')
    resources :courses, param: :internal_code do
      match :search, :on => :collection, :via => [:post, :get]
      get :questions, :on => :collection

      get :join, :on => :member
      get :leave, :on => :member

      resources :questions do
        resources :answers
        match :search, :on => :collection, :via => [:post, :get]
      end

      resources :discussions do
        resources :points
        match :search, :on => :collection, :via => [:post, :get]
      end

    end
  end
  resources :messages, only: [:show, :index] do
    resources :responses, only: [:create]
  end
  namespace :forum do
    get '/' => 'threads#index', as: 'index'
    resources :threads do
      resources :comments, only: [:create, :destroy, :edit, :update]
       get :watching, :on => :collection
    end
  end

  get '/about-us' => 'index#about', as: 'about'
  get '/terms-and-privacy' => 'index#terms', as: 'terms_and_privacy'
  get '/redirect' => 'index#redirect', as: 'redirect'
  resources :index, :only => [:index]

  devise_for :users, :controllers => {registrations: 'registrations' }
  devise_scope :user do
    resource :registration, only: [:new, :create, :edit, :update],
      path: 'users',
      path_names: {new: 'sign_up'},
      controller: 'devise/registrations',
      as: :user_registration do
        get :cancel
      end
  end
  
  resources :users, :except => [:new, :create, :destroy] do
    get 'messages/new' => 'messages#new'
    post 'messages' => 'messages#create', as: 'messages'
    get :market, :on => :member

  end

  namespace :advertise do

    get '/pricing' => 'index#pricing', as: 'pricing'

    resources :advertisements do
      get :activate, on: :member
    end

    resources :sponsors do
      get :activate, on: :member
    end

    resources :payments, only: [:new, :create, :index]
  end
  
  namespace :market do
     get '/' => 'index#index'

     resources :refreshes, :only => [:update, :refresh] do
       get :refresh, :on => :member
     end

     resources :accommodations do
       
       get 'messages/new' => '/messages#new'
       post 'messages' => '/messages#create', as: 'messages'

       match :search, :on => :collection, :via => [:post, :get]
     end

     resources :books do

       get 'messages/new' => '/messages#new'
       post 'messages' => '/messages#create', as: 'messages'
       match :search, :on => :collection, :via => [:post, :get]
     end

     resources :contacts
  end

  root 'market/index#index'

end

app/views/transactions/_form.html.haml
.row
  .small-24.columns
    = simple_form_for transaction, url: advertise_payments_path do |f|

      = render '/shared/form_errors', f: f

      .row
        .small-17.columns
          - if transaction.amount.nil? && current_user.credits < 0
            = f.input :amount, input_html: {:value => current_user.credits.abs, min: 0}
          - else
            = f.input :amount, label: 'Amount (USD)', input_html: {:min => 0}
        .small-7.columns
          = f.input :card_type, as: :select, collection: [["Visa", "visa"], ["MasterCard", "master"], ["Discover", "discover"], ["American Express", "american_express"]], include_blank: false

      .row
        .small-12.columns
          = f.input :first_name
        .small-12.columns
          = f.input :last_name
      = f.input :card_number, input_html: {:title => 'Use separators if you wish. Will strip them out'}, label: 'Card number (You can use separators. Spaces or dashes. etc)'
      .row
        .small-6.columns
          = f.input :month, as: :select, collection: (1..12).to_a, include_blank: false
        .small-6.columns
          = f.input :year, as: :select, collection: ((Time.now.year)..(12.years.from_now.year)).to_a, include_blank: false
        .small-5.columns
      .row
        .small-6.columns
          = f.input :verification_value, label: 'CCV', input_html: {:title => 'Usually the last 3 digits near your signature on your card'}

      = f.button :submit, 'Pay'