config/routes.rb
Rails.application.routes.draw do

  get '/users/:user_id/joined' => 'learn/courses#joined', as: 'user_joined_courses'
  namespace :learn do
    get '/', to: redirect('/learn/courses/questions')
    resources :courses, param: :internal_code do
      match :search, :on => :collection, :via => [:post, :get]
      get :questions, :on => :collection

      get :join, :on => :member
      get :leave, :on => :member

      resources :questions do
        resources :answers
        match :search, :on => :collection, :via => [:post, :get]
      end

      resources :discussions do
        resources :points
        match :search, :on => :collection, :via => [:post, :get]
      end

    end
  end
  resources :messages, only: [:show, :index] do
    resources :responses, only: [:create]
  end
  namespace :forum do
    get '/' => 'threads#index', as: 'index'
    resources :threads do
      resources :comments, only: [:create, :destroy, :edit, :update]
       get :watching, :on => :collection
    end
  end

  get '/about-us' => 'index#about', as: 'about'
  get '/terms-and-privacy' => 'index#terms', as: 'terms_and_privacy'
  get '/redirect' => 'index#redirect', as: 'redirect'
  resources :index, :only => [:index]

  devise_for :users, :controllers => {registrations: 'registrations' }
  devise_scope :user do
    resource :registration, only: [:new, :create, :edit, :update],
      path: 'users',
      path_names: {new: 'sign_up'},
      controller: 'devise/registrations',
      as: :user_registration do
        get :cancel
      end
  end
  
  resources :users, :except => [:new, :create, :destroy] do
    get 'messages/new' => 'messages#new'
    post 'messages' => 'messages#create', as: 'messages'
    get :market, :on => :member

  end

  namespace :advertise do

    get '/pricing' => 'index#pricing', as: 'pricing'

    resources :advertisements do
      get :activate, on: :member
    end

    resources :sponsors do
      get :activate, on: :member
    end

    resources :payments, only: [:new, :create, :index]
  end
  
  namespace :market do
     get '/' => 'index#index'

     resources :refreshes, :only => [:update, :refresh] do
       get :refresh, :on => :member
     end

     resources :accommodations do
       
       get 'messages/new' => '/messages#new'
       post 'messages' => '/messages#create', as: 'messages'

       match :search, :on => :collection, :via => [:post, :get]
     end

     resources :books do

       get 'messages/new' => '/messages#new'
       post 'messages' => '/messages#create', as: 'messages'
       match :search, :on => :collection, :via => [:post, :get]
     end

     resources :contacts
  end

  root 'market/index#index'

end

app/models/forum.rb
module Forum
  def self.table_name_prefix
    'forum_'
  end
end

app/models/forum/comment.rb
module Forum
  class Comment < ActiveRecord::Base

    include ::IdentityCache

    STATUSES = %w(visible deleted)

    belongs_to :user
    belongs_to :thread, touch: true

    before_validation :prepare_data

    validates_presence_of :content
    validates_presence_of :reason, if: lambda {|c| c.status.present? && c.status != 'visible'}

    def cached_thread
      Rails.cache.fetch([self.thread]) do
        self.thread
      end
    end

    def self.statuses(for_select = false)
      
      statuses = STATUSES.sort

      if for_select
        statuses = statuses.collect do |status|
          [status.humanize, status]
        end
      end

      statuses
    end

    protected

      def prepare_data
        self.content = self.content.strip
        self.status = 'visibile' if self.status.nil?
      end

  end
end

app/models/forum/thread.rb
module Forum
  class Thread < ActiveRecord::Base
    include ::IdentityCache

    CATEGORIES = %w(campus residence news events general computers bazido study_center)
    STATUSES = %w(closed banned open)
    
    belongs_to :user
    has_many :comments, dependent: :destroy, class_name: 'Comment'
    has_many :watchers, as: :watchable, class_name: 'Watch'
    # cache_has_many :comments, inverse_name: :comment, embed: true
    # cache_has_many :watchers, inverse_name: :watchable

    before_validation :prepare_data
    after_commit :flush_cache

    validates_presence_of :title
    validates_presence_of :content
    validates_presence_of :category
    validates_presence_of :reason, if: lambda {|c| c.status.present? && c.status != 'open'}

    validates_length_of :title, within: 10..255
    validates_length_of :content, minimum: 10

    validates_inclusion_of :category, in: CATEGORIES
    validates_inclusion_of :status, in: STATUSES

    # include ::Elasticsearch::Model
    # include ::Elasticsearch::Model::Callbacks

    # settings index: { number_of_shards: ::Market::NUMBER_OF_ELASTICSEARCH_SHARDS } do

    #   mappings dynamic: 'false' do
    #     indexes :title, analyzer: 'english'
    #     indexes :content, analyzer: 'english'
    #   end
    # end

    scope :for_user, lambda {|user|
      joins(:comments).where('forum_comments.thread_id=forum_threads.id AND forum_comments.user_id=?', user.id).references(:forum_comments).select('DISTINCT(forum_threads.id), forum_threads.*')
    }

    def flush_cache
      keys = CATEGORIES.collect do |category|
        [self.institution_website, category]
      end

      Rails.cache.delete(keys)
    end

    def self.cached_for_institution(institution_website, category, page)
      threads = Rails.cache.fetch([institution_website, category]) do
        threads = Forum::Thread.where('institution_website=?', institution_website).includes(:comments, :user)

        if category.present?
          threads = threads.where(category: category)
        end

        threads = threads.order(updated_at: :DESC)
        threads
      end

      threads.page(page)
    end

    def self.categories(for_select = false)

      categories = CATEGORIES.sort
      if for_select
        categories = categories.collect do |category|
          [category.humanize, category]
        end
      end

      categories
    end

    def self.statuses(for_select = false)
      
      statuses = STATUSES.sort

      if for_select
        statuses = statuses.collect do |status|
          [status.humanize, status]
        end
      end

      statuses
    end

    def cached_visible_comment_count
      Rails.cache.fetch([self,'comment_count']) do
        self.comments.where(status: 'visible').count
      end
    end

    protected

      def prepare_data
        self.title = self.title.split.join(' ')
        self.content = self.content.strip
        self.category = self.category.strip.downcase
        self.status = 'open' if self.status.nil?
      end

  end
end

app/controllers/forum/application_controller.rb
require_dependency "forum/application_controller"

module Forum
  class ApplicationController < ::ApplicationController #ActionController::Base

    before_action :authenticate_user! # , :except => [:show]

    protected


  end
end

app/controllers/forum/comments_controller.rb
require_dependency "forum/application_controller"

module Forum
  class CommentsController < ApplicationController

    before_action :load_resources

    def create
      unauthorized! if cannot?(:comment, @thread)
      unauthorized! if cannot?(:create, Comment.new(thread: @thread))

      @comment = @thread.comments.build(comment_params)
      @comment.user_id = current_user.id
      @comment.status = 'visible' if @comment.status.nil?
      
      if @comment.save
        @thread.touch

        # Create or edit watcher for this current user
          update_watcher(@thread, current_user, 'Forum', 'forum_threads_notifications_count')
          # watcher = @thread.watchers.where(user_id: current_user.id).where(status: 'open').first
          # if watcher.nil?
          #   watcher = @thread.watchers.build(user_id: current_user.id, status: 'open', application_space: 'Forum', read: true, checked_at: Time.now)
          # end

          # watcher.read = true
          # watcher.save

        # ========================================
        # Let all other interested users know they have not read this new comment
          # @thread.watchers.where(status: 'open').where(read: true).update_all(read: false)
        # ========================================


        flash[:notice] = "Successfully responded to the post"
        redirect_to forum_thread_path(@thread, page: @thread.comments.page(params[:page]).num_pages, anchor: @comment.id)
      else
        @comments = @thread.comments
        flash[:forum_comment_content] = @comment.content
        flash[:forum_comment_errors] = @comment.errors
        redirect_to @thread
      end

    end

    def edit
    end

    def update
    end

    def destroy
      unauthorized! if cannot? :destroy, @comment

      if @comment.user_id == current_user.id
        reason = 'Original poster\'s choice'
        content = '-- Deleted content --'
      else
        reason = 'Due to moderation reasons'
        # Leave content as proof
        content = @comment.content
      end


      if @comment.update_attributes({status: 'deleted', content: content, reason: reason})
        flash[:notice] = "Successfully deleted the post"
      else
        flash[:alert] = "Could not delete the post"
      end
      redirect_to @thread
    end

    protected

      def load_resources
        @thread = Forum::Thread.page(params[:page]).find(params[:thread_id])

          @comment = Forum::Comment.find_by_id(params[:id])# @thread.comments.where(id: params[:thread_id]).first
      end

      def comment_params
        param_array = [:content]

        if can? :moderate, @thread
          param_array << :status
          param_array << :reason
        end

        params.require(:forum_comment).permit(param_array)
      end
  end
end

app/controllers/forum/index_controller.rb
require_dependency "forum/application_controller"

module Forum
  class IndexController < ApplicationController

    before_action :load_adverts, except: [:create, :update, :destroy]

    def index
    end
  end
end

app/controllers/forum/threads_controller.rb
require_dependency "forum/application_controller"

# Remeber to always use Forum::Thread else you'll be calling Ruby's thread


module Forum
  class ThreadsController < ApplicationController

    before_action :load_thread, except: [:new, :create, :index, :watching]
    before_action :load_threads, only: [:index, :watching]
    before_action :load_adverts, except: [:create, :update, :destroy]
    load_and_authorize_resource

    respond_to :html

    def new
      @thread = Forum::Thread.new(category: params[:category], status: 'open')
    end

    def create
      @thread = Forum::Thread.new(thread_params)

      @thread.user_id = current_user.id
      @thread.institution_website = current_user.profile.institution_website

      if @thread.save
        create_watcher(@thread, current_user, 'Forum')
        # watcher = @thread.watchers.create(user_id: current_user.id, checked_at: Time.now, status: 'open', application_space: 'Forum', read: true)
        # watcher.save
        flash[:notice] = 'Post created succesfully'
      end

      respond_with(@thread)
    end

    def edit
    end

    def update
      @thread = Forum::Thread.find(params[:id])
      @thread.assign_attributes(thread_params)
      if @thread.save
        flash[:notice] = 'Successfully updated post'
      end

      respond_with(@thread)
    end

    def show
      @comment = Forum::Comment.new(status: :visible, content: flash[:forum_comment_content])
      @comments = @thread.comments # .page(params[:page])

      # Mark the user as having read this thread
      reset_watcher(@thread, current_user, 'forum_threads_notifications_count')
      # @thread.watchers.where(user_id: current_user.id).where(read: false).update_all(read: true)
      # Rails.cache.delete([current_user, 'forum_threads_notifications_count'])

      # Copy possible errors into the comment if from another comment
      if flash[:forum_comment_errors].present?
        flash[:forum_comment_errors].each do |key, value|
          if value.is_a? Array

            value.each do |error|
              @comment.errors.add(key, error)
            end

          else
            @comment.errors.add(key, value)
          end
        end
      end
    end

    def destroy
      if @thread.destroy
        flash[:notice] = "Successfully deleted what you said"
      else
        flash[:alert] = "Could not delete what you said due to technical error"
      end

      redirect_to forum_threads_path
    end

    def index
    end

    def watching
      @threads = current_user.watching_forum_threads(@threads) # @threads.for_user(current_user).page(params[:page])
      render action: :index
    end

    protected

      def thread_params
        param_array = [:title, :content, :category]

        if can? :moderate, @thread
          param_array << :status
          param_array << :reason
        end

        params.require(:forum_thread).permit(param_array)
      end

      def load_thread
          @thread = Forum::Thread.fetch(params[:id])
      end

      def load_threads
        @threads = Forum::Thread.cached_for_institution(current_user.profile.institution_website, params[:category], params[:page]) 

        if can? :moderate, @thread
          if params[:status].present?
            @threads = @threads.where(status: params[:status])
          end
        end

        @threads
      end
  end
end

app/helpers/forum/comments_helper.rb
module Forum::CommentsHelper
end

app/helpers/forum/index_helper.rb
module Forum::IndexHelper
end

app/helpers/forum/threads_helper.rb
module Forum::ThreadsHelper
end

app/views/forum/threads/_form.html.haml
= simple_form_for thread do |f|

  = render '/shared/form_errors', f: f

  = f.input :title
  = f.input :category, collection: Forum::Thread.categories(true), include_blank: false
  = f.input :content

  - if can? :moderate, thread
    = f.input :status, collection: Forum::Thread.statuses(true), include_blank: false
    = f.input :reason

  - if thread.id == nil
    = f.button :submit, 'Say it'
  - else
    = f.button :submit, 'Update Post'

app/views/forum/threads/_index_thread.html.haml
= thread.title
= h(truncate(user_refresh_name(thread.comments.last.user.profile), length: 15))
= link_to "#{h(truncate(user_refresh_name(thread.user.profile), length: 18))}", thread.user, :title => h(thread.user.profile.full_name)
= thread.created_at.strftime('%e %b \'%y at %H:%M')
= thread.comments.count

app/views/forum/threads/_table.html.haml
- if threads.any?
  .index-threads
    %table{:width => '100%'}
      %thead
        %tr
          %th
            Title
          %th
            Replies
          %th
            Most recent
      %tbody
        - threads.each do |thread|
          %tr{class: forum_thread_status(thread)}
            %td
              = link_to h(thread.title), thread
            %td
              = h(thread.cached_visible_comment_count)
            -# %td
              = thread.created_at.strftime('%e %b \'%y at %H:%M')
            %td
              .row
                .small-24.columns
                  - if thread.cached_visible_comment_count > 0
                    = link_to h(truncate(user_refresh_name(thread.comments.last.user.profile), length: 18)), thread.comments.last.user, :title => h(thread.comments.last.user.profile.full_name) 
                  - else
                    = link_to h(truncate(user_refresh_name(thread.user.profile), length: 18)), thread.user, :title => h(thread.user.profile.full_name)

                .small-24.columns
                  = thread.updated_at.strftime('%d %b \'%y at %H:%M')

    .pagination
      = paginate(threads)

- else
  .empty-list
    No threads to show

app/views/forum/threads/_thread.html.haml
- prepend :side_bar do
  %h4.title
    = link_to thread.category.humanize, forum_threads_path(category: thread.category)

%h4.title
  = h(thread.title)
.post
  = simple_format(h(thread.content))
  = render '/shared/user', object: thread, edit_path: edit_forum_thread_path(thread), delete_path: forum_thread_path(thread)

  %h5.sub-posts-count
    = "#{pluralize(comments.where(status: 'visible').count, 'response')}"
  - if thread.cached_visible_comment_count > 0
    .sub-posts
      = render comments

  - else
    .empty-list
      No responses yet.
  - if can? :comment, @thread
    .sub-post-form
      = render '/forum/comments/form', empty_comment: empty_comment, path: forum_thread_comments_path(@thread)
  - else
    - if !thread.reason
      Thread closed by original poster
    - else
      Thread closed:
      = h(thread.reason)

app/views/forum/threads/edit.html.haml
%h4
  Edit post

= render '/forum/threads/form', thread: @thread

app/views/forum/threads/index.html.haml
- if action_name == 'watching'
  %h4
    Threads you are watching
-# - elsif action_name == 'index' && params[:category].present?
  %h4
    = "Category: #{params[:category].humanize}"
- elsif action_name == 'index'
  %h4
    All threads ever posted

-# Show the category in the top right corner if it's there
- if params[:category].present?
  - if Forum::Thread.categories.include?(params[:category])
    - prepend :side_bar do
      %h5.category-title
        = params[:category].humanize

    -# - prepend :content do
      %h5
        = params[:category].humanize

  - else
    - prepend :side_bar do
      %h5.category-title
        Unknown
-# ======================================================

= render '/forum/threads/table', threads: @threads

app/views/forum/threads/new.html.haml
%h3
  Say something

= render '/forum/threads/form', thread: @thread

app/views/forum/threads/show.html.haml
= render '/forum/threads/thread', thread: @thread, empty_comment: @comment, comments: @comments